on:
  workflow_dispatch:

jobs:
  deployBicep:
    runs-on: ubuntu-latest
    name: deploy a bicep file
    steps:
      - uses: actions/checkout@v3
      
      # This step shows that bicep is not installed on start of pipeline
      - shell: bash
        run: az bicep version
        continue-on-error: true
      
      # This action will restore bicep from cache or install if not found in cache
      - uses: simonwahlin/CompositeActionTest@v3
      
      # This action will authenticate to Azure
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.CREDENTIALS }}

      # Simple bash step that lists current bicep version
      # and deploys a template (az cli is included in ubuntu runner)
      #- name: "Deploy template"
      #  shell: bash
      #  run: |
      #    az bicep version
      #    az deployment sub create --location westeurope --template-file main.bicep
          
      - uses: azure/CLI@v1
        with:
          inlineScript: |
            echo "HOME: '${home}'"
            echo "WSPAth: '${GITHUB_WORKSPACE}'"
            ls $GITHUB_WORKSPACE
            ls ~
            az config get
            ls /root -R
            ls /github/home
            
            
          
