on:
  workflow_dispatch:

jobs:
  deployBicep:
    runs-on: ubuntu-latest
    name: deploy a bicep file
    steps:
      - uses: actions/checkout@v3
      
      - uses: simonwahlin/CompositeActionTest@v1
      
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.CREDENTIALS }}
      

          
      - name: "Deploy template"
        shell: bash
        run: |
          az deployment sub create --location westeurope --template-file main.bicep
        
      - name: Azure CLI script
        uses: azure/CLI@v1
        with:
          azcliversion: 2.43.0
          inlineScript: |
            echo "Variable AZURE_CONFIG_DIR has value: ${AZURE_CONFIG_DIR}"
            ls /home/runner
