on:
  workflow_dispatch:

jobs:
  deployBicep:
    runs-on: ubuntu-latest
    name: deploy a bicep file
    steps:
      - uses: actions/checkout@v3
      
      # This step shows that bicep is not installed on start of pipeline
      - shell: bash
        run: az bicep version
        continue-on-error: true
      
      # This action will restore bicep from cache or install if not found in cache
      - uses: SimonWahlin/AzCliBicepSetup@b4a79e0b1fbed5e571b098ef45fc9b62d2a2bffe
        with:
          bicepversion: v0.12.40
      
      # This step shows that bicep is now installed
      - shell: bash
        run: az bicep version
        
      # This action will authenticate to Azure (requires CREDENTIALS secret)
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.CREDENTIALS }}

      # Simple bash step that lists current bicep version
      # and deploys a template (az cli is included in ubuntu runner)
      - name: "Deploy template"
        shell: bash
        run: |
          az bicep version
          az deployment sub create --location westeurope --template-file main.bicep
          
      - uses: Azure/arm-deploy@v1
        with:
          scope: subscription
          region: westeurope
          template: main.bicep
          additionalArguments: --only-show-errors
          
